#  .travis.yml             Python projects                    Date : 2018-04-06

#  Check the BUILD STATUS page to see if your build passes or fails:
#            For PUBLIC  repositories:  https://travis-ci.org/auth
#            For PRIVATE repositories:  https://travis-ci.com/auth


#  PHASE - the sequential steps of a job. 
#      For example, the install phase, comes before the script phase, 
#      which comes before the optional deploy phase.


#  REFERENCES
#  trusty:= Ubuntu 14.04 distribution.
#  Python setup: https://docs.travis-ci.com/user/languages/python
#  Install dependencies: https://docs.travis-ci.com/user/installing-dependencies
#  Customization: https://docs.travis-ci.com/user/customizing-the-build
#  Notifications: https://docs.travis-ci.com/user/notifications
#  Newbie: https://docs.travis-ci.com/user/for-beginners


#  CHANGE LOG
#  2018-04-07  Add reference notes and comments.
#  2018-04-06  First version, pure from pandas_datareader


# ==============================================================================

sudo: false

     #  "false" implies CONTAINER-BASED, default for new projects. 
     #  Linux Ubuntu environment running in a container. 
     #  Does NOT support the use of sudo, setuid, or setgid.
     #
     #  SUDO-ENABLED runs on full virtual machine. It starts a little slower, 
     #  but it has more computational resources, and 
     #  supports the use of sudo, setuid, and setgid.
     #  Setting is "sudo: enabled"

language: python

env:
  global:
    #  DOCTR deploy key: automatically deploying docs from Travis CI 
    #  to GitHub pages. Doctr requires python >=3.5
    #  Ref: https://github.com/drdoctr/doctr
    - secure: "foo"


matrix:
  fast_finish: true
  include:
  - dist: trusty
    env:
      - PYTHON=2.7 PANDAS=0.22
  - dist: trusty
    env:
      - PYTHON=3.6 PANDAS=0.21.1
  - dist: trusty
    env:
      - PYTHON=3.6 PANDAS=0.22 DOCBUILD=true
  # In allow failures
  - dist: trusty
    env:
      - PYTHON=3.6 PANDAS="MASTER"
  allow_failures:
    - dist: trusty
      env:
        - PYTHON=3.6 PANDAS="MASTER"

install:
  - pip install -qq flake8
  #    Periodically update conditional, although conda update line
  #    will keep everything up-to-date:
  - if [[ "$PYTHON" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels pandas
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$PYTHON coverage setuptools html5lib lxml pytest pytest-cov wrapt
  - source activate test-environment
  - if [[ "$PANDAS" == "MASTER" ]]; then
      conda install numpy pytz python-dateutil;
      PRE_WHEELS="https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com";
      pip install --pre --upgrade --timeout=60 -f $PRE_WHEELS pandas;
    else
      conda install pandas=$PANDAS;
    fi
  - if [[ $DOCBUILD ]]; then
      conda install sphinx ipython matplotlib;
      pip install sphinx_rtd_theme doctr;
    fi
  - pip install beautifulsoup4
  #  - pip install coveralls --quiet
  #  #             ^for "after success:" section below.
  - conda list
  - python setup.py install


script:
    #  - export ENIGMA_API_KEY=$ENIGMA_API_KEY
    - pytest -s -r xX --cov-config .coveragerc --cov=pandas_datareader --cov-report xml:/tmp/cov-datareader.xml --junitxml=/tmp/datareader.xml
    - flake8 --version
    - flake8 pandas_datareader



#  _______________ 2018-04-06  pandas_datareader
#  
#  after_success:
#    - |
#      if [[ ${DOCBUILD} ]]; then
#        cd docs
#        make html && make html
#        cd ..
#        doctr deploy devel --build-tags
#        if [[ -z ${TRAVIS_TAG} ]]; then
#          echo "Not a tagged build."
#        else
#          doctr deploy stable --build-tags
#        fi
#      fi
#    - coveralls
#    #   See https://coveralls.io/features for COVERALLS


